server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: WARN
    com.sugang.user: DEBUG

spring:
  application:
    name: user-service

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      bindings:
        input:
          destination: ${KAFKA_TOPIC}
          content-type: application/json
          group: ${KAFKA_GROUP}
      kafka:
        binder:
          zkNodes: ${KAFKA_ZOOKEEPER}
          brokers: ${KAFKA_BROKER}
