server:
  port: 8081

spring:
  application:
    name: userService

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      bindings:
        input:
          destination: authToUser
          content-type: application/json
          group: userGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
